version: '3.8'

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/create_users_table.sql:/docker-entrypoint-initdb.d/create_users_table.sql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"